language: android
dist: trusty
andriod:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
jobs:
  include:
    - stage: build
      name: "Build"
      script: ./gradlew build
    - stage: test
      name: "Test"
      script: ./gradlew test
    - stage: build & test
      name: "Build & Test"
      script: ./gradlew build test
    - stage: lint
      name: "Lint"
      script: ./gradlew lint